# Generated by Django 6.0.5 on 2026-06-11 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado de inscripción')),
                ('progress_status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En progreso'), ('completed', 'Completado')], default='not_started', max_length=20, verbose_name='Estado del progreso')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Porcentaje de progreso')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
