# Generated by Django 6.0.5 on 2026-06-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_question_answeroption_quiz_question_quiz'),
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='enrollments.enrollment', verbose_name='Inscripción')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson', verbose_name='Lección')),
            ],
            options={
                'verbose_name': 'Progreso de lección',
                'verbose_name_plural': 'Progresos de lecciones',
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
