# Generated by Django 6.0.5 on 2026-06-11 02:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código del certificado')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Archivo PDF')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Certificado válido')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-issued_at'],
            },
        ),
    ]
