# Generated by Django 6.0.5 on 2026-07-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_quizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'verbose_name': 'Opción de respuesta', 'verbose_name_plural': 'Opciones de respuesta'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Lección', 'verbose_name_plural': 'Lecciones'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Examen', 'verbose_name_plural': 'Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Intento de examen', 'verbose_name_plural': 'Intentos de examen'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
    ]
